const COUNTRY_NAMES_BY_LOCALE: Record<string, Record<string, string>> = {
  en: {
    AD: 'Andorra',
    AE: 'United Arab Emirates',
    AF: 'Afghanistan',
    AG: 'Antigua & Barbuda',
    AI: 'Anguilla',
    AL: 'Albania',
    AM: 'Armenia',
    AO: 'Angola',
    AQ: 'Antarctica',
    AR: 'Argentina',
    AS: 'American Samoa',
    AT: 'Austria',
    AU: 'Australia',
    AW: 'Aruba',
    AX: 'Åland Islands',
    AZ: 'Azerbaijan',
    BA: 'Bosnia & Herzegovina',
    BB: 'Barbados',
    BD: 'Bangladesh',
    BE: 'Belgium',
    BF: 'Burkina Faso',
    BG: 'Bulgaria',
    BH: 'Bahrain',
    BI: 'Burundi',
    BJ: 'Benin',
    BL: 'St. Barthélemy',
    BM: 'Bermuda',
    BN: 'Brunei',
    BO: 'Bolivia',
    BQ: 'Caribbean Netherlands',
    BR: 'Brazil',
    BS: 'Bahamas',
    BT: 'Bhutan',
    BV: 'Bouvet Island',
    BW: 'Botswana',
    BY: 'Belarus',
    BZ: 'Belize',
    CA: 'Canada',
    CC: 'Cocos (Keeling) Islands',
    CD: 'Congo - Kinshasa',
    CF: 'Central African Republic',
    CG: 'Congo - Brazzaville',
    CH: 'Switzerland',
    CI: 'Côte d’Ivoire',
    CK: 'Cook Islands',
    CL: 'Chile',
    CM: 'Cameroon',
    CN: 'China',
    CO: 'Colombia',
    CR: 'Costa Rica',
    CU: 'Cuba',
    CV: 'Cape Verde',
    CW: 'Curaçao',
    CX: 'Christmas Island',
    CY: 'Cyprus',
    CZ: 'Czechia',
    DE: 'Germany',
    DJ: 'Djibouti',
    DK: 'Denmark',
    DM: 'Dominica',
    DO: 'Dominican Republic',
    DZ: 'Algeria',
    EC: 'Ecuador',
    EE: 'Estonia',
    EG: 'Egypt',
    EH: 'Western Sahara',
    ER: 'Eritrea',
    ES: 'Spain',
    ET: 'Ethiopia',
    FI: 'Finland',
    FJ: 'Fiji',
    FK: 'Falkland Islands',
    FM: 'Micronesia',
    FO: 'Faroe Islands',
    FR: 'France',
    GA: 'Gabon',
    GB: 'United Kingdom',
    GD: 'Grenada',
    GE: 'Georgia',
    GF: 'French Guiana',
    GG: 'Guernsey',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GL: 'Greenland',
    GM: 'Gambia',
    GN: 'Guinea',
    GP: 'Guadeloupe',
    GQ: 'Equatorial Guinea',
    GR: 'Greece',
    GS: 'South Georgia & South Sandwich Islands',
    GT: 'Guatemala',
    GU: 'Guam',
    GW: 'Guinea-Bissau',
    GY: 'Guyana',
    HK: 'Hong Kong SAR China',
    HM: 'Heard & McDonald Islands',
    HN: 'Honduras',
    HR: 'Croatia',
    HT: 'Haiti',
    HU: 'Hungary',
    ID: 'Indonesia',
    IE: 'Ireland',
    IL: 'Israel',
    IM: 'Isle of Man',
    IN: 'India',
    IO: 'British Indian Ocean Territory',
    IQ: 'Iraq',
    IR: 'Iran',
    IS: 'Iceland',
    IT: 'Italy',
    JE: 'Jersey',
    JM: 'Jamaica',
    JO: 'Jordan',
    JP: 'Japan',
    KE: 'Kenya',
    KG: 'Kyrgyzstan',
    KH: 'Cambodia',
    KI: 'Kiribati',
    KM: 'Comoros',
    KN: 'St. Kitts & Nevis',
    KP: 'North Korea',
    KR: 'South Korea',
    KW: 'Kuwait',
    KY: 'Cayman Islands',
    KZ: 'Kazakhstan',
    LA: 'Laos',
    LB: 'Lebanon',
    LC: 'St. Lucia',
    LI: 'Liechtenstein',
    LK: 'Sri Lanka',
    LR: 'Liberia',
    LS: 'Lesotho',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    LV: 'Latvia',
    LY: 'Libya',
    MA: 'Morocco',
    MC: 'Monaco',
    MD: 'Moldova',
    ME: 'Montenegro',
    MF: 'St. Martin',
    MG: 'Madagascar',
    MH: 'Marshall Islands',
    MK: 'North Macedonia',
    ML: 'Mali',
    MM: 'Myanmar (Burma)',
    MN: 'Mongolia',
    MO: 'Macao SAR China',
    MP: 'Northern Mariana Islands',
    MQ: 'Martinique',
    MR: 'Mauritania',
    MS: 'Montserrat',
    MT: 'Malta',
    MU: 'Mauritius',
    MV: 'Maldives',
    MW: 'Malawi',
    MX: 'Mexico',
    MY: 'Malaysia',
    MZ: 'Mozambique',
    NA: 'Namibia',
    NC: 'New Caledonia',
    NE: 'Niger',
    NF: 'Norfolk Island',
    NG: 'Nigeria',
    NI: 'Nicaragua',
    NL: 'Netherlands',
    NO: 'Norway',
    NP: 'Nepal',
    NR: 'Nauru',
    NU: 'Niue',
    NZ: 'New Zealand',
    OM: 'Oman',
    PA: 'Panama',
    PE: 'Peru',
    PF: 'French Polynesia',
    PG: 'Papua New Guinea',
    PH: 'Philippines',
    PK: 'Pakistan',
    PL: 'Poland',
    PM: 'St. Pierre & Miquelon',
    PN: 'Pitcairn Islands',
    PR: 'Puerto Rico',
    PS: 'Palestinian Territories',
    PT: 'Portugal',
    PW: 'Palau',
    PY: 'Paraguay',
    QA: 'Qatar',
    RE: 'Réunion',
    RO: 'Romania',
    RS: 'Serbia',
    RU: 'Russia',
    RW: 'Rwanda',
    SA: 'Saudi Arabia',
    SB: 'Solomon Islands',
    SC: 'Seychelles',
    SD: 'Sudan',
    SE: 'Sweden',
    SG: 'Singapore',
    SH: 'St. Helena',
    SI: 'Slovenia',
    SJ: 'Svalbard & Jan Mayen',
    SK: 'Slovakia',
    SL: 'Sierra Leone',
    SM: 'San Marino',
    SN: 'Senegal',
    SO: 'Somalia',
    SR: 'Suriname',
    SS: 'South Sudan',
    ST: 'São Tomé & Príncipe',
    SV: 'El Salvador',
    SX: 'Sint Maarten',
    SY: 'Syria',
    SZ: 'Eswatini',
    TC: 'Turks & Caicos Islands',
    TD: 'Chad',
    TF: 'French Southern Territories',
    TG: 'Togo',
    TH: 'Thailand',
    TJ: 'Tajikistan',
    TK: 'Tokelau',
    TL: 'Timor-Leste',
    TM: 'Turkmenistan',
    TN: 'Tunisia',
    TO: 'Tonga',
    TR: 'Türkiye',
    TT: 'Trinidad & Tobago',
    TV: 'Tuvalu',
    TW: 'Taiwan',
    TZ: 'Tanzania',
    UA: 'Ukraine',
    UG: 'Uganda',
    UM: 'U.S. Outlying Islands',
    US: 'United States',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VA: 'Vatican City',
    VC: 'St. Vincent & Grenadines',
    VE: 'Venezuela',
    VG: 'British Virgin Islands',
    VI: 'U.S. Virgin Islands',
    VN: 'Vietnam',
    VU: 'Vanuatu',
    WF: 'Wallis & Futuna',
    WS: 'Samoa',
    YE: 'Yemen',
    YT: 'Mayotte',
    ZA: 'South Africa',
    ZM: 'Zambia',
    ZW: 'Zimbabwe',
  },
  es: {
    AD: 'Andorra',
    AE: 'Emiratos Árabes Unidos',
    AF: 'Afganistán',
    AG: 'Antigua y Barbuda',
    AI: 'Anguila',
    AL: 'Albania',
    AM: 'Armenia',
    AO: 'Angola',
    AQ: 'Antártida',
    AR: 'Argentina',
    AS: 'Samoa Americana',
    AT: 'Austria',
    AU: 'Australia',
    AW: 'Aruba',
    AX: 'Islas Aland',
    AZ: 'Azerbaiyán',
    BA: 'Bosnia y Herzegovina',
    BB: 'Barbados',
    BD: 'Bangladés',
    BE: 'Bélgica',
    BF: 'Burkina Faso',
    BG: 'Bulgaria',
    BH: 'Baréin',
    BI: 'Burundi',
    BJ: 'Benín',
    BL: 'San Bartolomé',
    BM: 'Bermudas',
    BN: 'Brunéi',
    BO: 'Bolivia',
    BQ: 'Caribe neerlandés',
    BR: 'Brasil',
    BS: 'Bahamas',
    BT: 'Bután',
    BV: 'Isla Bouvet',
    BW: 'Botsuana',
    BY: 'Bielorrusia',
    BZ: 'Belice',
    CA: 'Canadá',
    CC: 'Islas Cocos',
    CD: 'República Democrática del Congo',
    CF: 'República Centroafricana',
    CG: 'Congo',
    CH: 'Suiza',
    CI: 'Côte d’Ivoire',
    CK: 'Islas Cook',
    CL: 'Chile',
    CM: 'Camerún',
    CN: 'China',
    CO: 'Colombia',
    CR: 'Costa Rica',
    CU: 'Cuba',
    CV: 'Cabo Verde',
    CW: 'Curazao',
    CX: 'Isla de Navidad',
    CY: 'Chipre',
    CZ: 'Chequia',
    DE: 'Alemania',
    DJ: 'Yibuti',
    DK: 'Dinamarca',
    DM: 'Dominica',
    DO: 'República Dominicana',
    DZ: 'Argelia',
    EC: 'Ecuador',
    EE: 'Estonia',
    EG: 'Egipto',
    EH: 'Sáhara Occidental',
    ER: 'Eritrea',
    ES: 'España',
    ET: 'Etiopía',
    FI: 'Finlandia',
    FJ: 'Fiyi',
    FK: 'Islas Malvinas',
    FM: 'Micronesia',
    FO: 'Islas Feroe',
    FR: 'Francia',
    GA: 'Gabón',
    GB: 'Reino Unido',
    GD: 'Granada',
    GE: 'Georgia',
    GF: 'Guayana Francesa',
    GG: 'Guernesey',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GL: 'Groenlandia',
    GM: 'Gambia',
    GN: 'Guinea',
    GP: 'Guadalupe',
    GQ: 'Guinea Ecuatorial',
    GR: 'Grecia',
    GS: 'Islas Georgia del Sur y Sandwich del Sur',
    GT: 'Guatemala',
    GU: 'Guam',
    GW: 'Guinea-Bisáu',
    GY: 'Guyana',
    HK: 'RAE de Hong Kong (China)',
    HM: 'Islas Heard y McDonald',
    HN: 'Honduras',
    HR: 'Croacia',
    HT: 'Haití',
    HU: 'Hungría',
    ID: 'Indonesia',
    IE: 'Irlanda',
    IL: 'Israel',
    IM: 'Isla de Man',
    IN: 'India',
    IO: 'Territorio Británico del Océano Índico',
    IQ: 'Irak',
    IR: 'Irán',
    IS: 'Islandia',
    IT: 'Italia',
    JE: 'Jersey',
    JM: 'Jamaica',
    JO: 'Jordania',
    JP: 'Japón',
    KE: 'Kenia',
    KG: 'Kirguistán',
    KH: 'Camboya',
    KI: 'Kiribati',
    KM: 'Comoras',
    KN: 'San Cristóbal y Nieves',
    KP: 'Corea del Norte',
    KR: 'Corea del Sur',
    KW: 'Kuwait',
    KY: 'Islas Caimán',
    KZ: 'Kazajistán',
    LA: 'Laos',
    LB: 'Líbano',
    LC: 'Santa Lucía',
    LI: 'Liechtenstein',
    LK: 'Sri Lanka',
    LR: 'Liberia',
    LS: 'Lesoto',
    LT: 'Lituania',
    LU: 'Luxemburgo',
    LV: 'Letonia',
    LY: 'Libia',
    MA: 'Marruecos',
    MC: 'Mónaco',
    MD: 'Moldavia',
    ME: 'Montenegro',
    MF: 'San Martín',
    MG: 'Madagascar',
    MH: 'Islas Marshall',
    MK: 'Macedonia del Norte',
    ML: 'Mali',
    MM: 'Myanmar (Birmania)',
    MN: 'Mongolia',
    MO: 'RAE de Macao (China)',
    MP: 'Islas Marianas del Norte',
    MQ: 'Martinica',
    MR: 'Mauritania',
    MS: 'Montserrat',
    MT: 'Malta',
    MU: 'Mauricio',
    MV: 'Maldivas',
    MW: 'Malaui',
    MX: 'México',
    MY: 'Malasia',
    MZ: 'Mozambique',
    NA: 'Namibia',
    NC: 'Nueva Caledonia',
    NE: 'Níger',
    NF: 'Isla Norfolk',
    NG: 'Nigeria',
    NI: 'Nicaragua',
    NL: 'Países Bajos',
    NO: 'Noruega',
    NP: 'Nepal',
    NR: 'Nauru',
    NU: 'Niue',
    NZ: 'Nueva Zelanda',
    OM: 'Omán',
    PA: 'Panamá',
    PE: 'Perú',
    PF: 'Polinesia Francesa',
    PG: 'Papúa Nueva Guinea',
    PH: 'Filipinas',
    PK: 'Pakistán',
    PL: 'Polonia',
    PM: 'San Pedro y Miquelón',
    PN: 'Islas Pitcairn',
    PR: 'Puerto Rico',
    PS: 'Territorios Palestinos',
    PT: 'Portugal',
    PW: 'Palaos',
    PY: 'Paraguay',
    QA: 'Catar',
    RE: 'Reunión',
    RO: 'Rumanía',
    RS: 'Serbia',
    RU: 'Rusia',
    RW: 'Ruanda',
    SA: 'Arabia Saudí',
    SB: 'Islas Salomón',
    SC: 'Seychelles',
    SD: 'Sudán',
    SE: 'Suecia',
    SG: 'Singapur',
    SH: 'Santa Elena',
    SI: 'Eslovenia',
    SJ: 'Svalbard y Jan Mayen',
    SK: 'Eslovaquia',
    SL: 'Sierra Leona',
    SM: 'San Marino',
    SN: 'Senegal',
    SO: 'Somalia',
    SR: 'Surinam',
    SS: 'Sudán del Sur',
    ST: 'Santo Tomé y Príncipe',
    SV: 'El Salvador',
    SX: 'Sint Maarten',
    SY: 'Siria',
    SZ: 'Esuatini',
    TC: 'Islas Turcas y Caicos',
    TD: 'Chad',
    TF: 'Territorios Australes Franceses',
    TG: 'Togo',
    TH: 'Tailandia',
    TJ: 'Tayikistán',
    TK: 'Tokelau',
    TL: 'Timor-Leste',
    TM: 'Turkmenistán',
    TN: 'Túnez',
    TO: 'Tonga',
    TR: 'Turquía',
    TT: 'Trinidad y Tobago',
    TV: 'Tuvalu',
    TW: 'Taiwán',
    TZ: 'Tanzania',
    UA: 'Ucrania',
    UG: 'Uganda',
    UM: 'Islas menores alejadas de EE. UU.',
    US: 'Estados Unidos',
    UY: 'Uruguay',
    UZ: 'Uzbekistán',
    VA: 'Ciudad del Vaticano',
    VC: 'San Vicente y las Granadinas',
    VE: 'Venezuela',
    VG: 'Islas Vírgenes Británicas',
    VI: 'Islas Vírgenes de EE. UU.',
    VN: 'Vietnam',
    VU: 'Vanuatu',
    WF: 'Wallis y Futuna',
    WS: 'Samoa',
    YE: 'Yemen',
    YT: 'Mayotte',
    ZA: 'Sudáfrica',
    ZM: 'Zambia',
    ZW: 'Zimbabue',
  },
  ru: {
    AD: 'Андорра',
    AE: 'ОАЭ',
    AF: 'Афганистан',
    AG: 'Антигуа и Барбуда',
    AI: 'Ангилья',
    AL: 'Албания',
    AM: 'Армения',
    AO: 'Ангола',
    AQ: 'Антарктида',
    AR: 'Аргентина',
    AS: 'Американское Самоа',
    AT: 'Австрия',
    AU: 'Австралия',
    AW: 'Аруба',
    AX: 'Аландские о-ва',
    AZ: 'Азербайджан',
    BA: 'Босния и Герцеговина',
    BB: 'Барбадос',
    BD: 'Бангладеш',
    BE: 'Бельгия',
    BF: 'Буркина-Фасо',
    BG: 'Болгария',
    BH: 'Бахрейн',
    BI: 'Бурунди',
    BJ: 'Бенин',
    BL: 'Сен-Бартелеми',
    BM: 'Бермудские о-ва',
    BN: 'Бруней',
    BO: 'Боливия',
    BQ: 'Бонэйр, Синт-Эстатиус и Саба',
    BR: 'Бразилия',
    BS: 'Багамы',
    BT: 'Бутан',
    BV: 'о-в Буве',
    BW: 'Ботсвана',
    BY: 'Беларусь',
    BZ: 'Белиз',
    CA: 'Канада',
    CC: 'Кокосовые о-ва',
    CD: 'Конго - Киншаса',
    CF: 'Центрально-Африканская Республика',
    CG: 'Конго - Браззавиль',
    CH: 'Швейцария',
    CI: 'Кот-д’Ивуар',
    CK: 'о-ва Кука',
    CL: 'Чили',
    CM: 'Камерун',
    CN: 'Китай',
    CO: 'Колумбия',
    CR: 'Коста-Рика',
    CU: 'Куба',
    CV: 'Кабо-Верде',
    CW: 'Кюрасао',
    CX: 'о-в Рождества',
    CY: 'Кипр',
    CZ: 'Чехия',
    DE: 'Германия',
    DJ: 'Джибути',
    DK: 'Дания',
    DM: 'Доминика',
    DO: 'Доминиканская Республика',
    DZ: 'Алжир',
    EC: 'Эквадор',
    EE: 'Эстония',
    EG: 'Египет',
    EH: 'Западная Сахара',
    ER: 'Эритрея',
    ES: 'Испания',
    ET: 'Эфиопия',
    FI: 'Финляндия',
    FJ: 'Фиджи',
    FK: 'Фолклендские о-ва',
    FM: 'Федеративные Штаты Микронезии',
    FO: 'Фарерские о-ва',
    FR: 'Франция',
    GA: 'Габон',
    GB: 'Великобритания',
    GD: 'Гренада',
    GE: 'Грузия',
    GF: 'Французская Гвиана',
    GG: 'Гернси',
    GH: 'Гана',
    GI: 'Гибралтар',
    GL: 'Гренландия',
    GM: 'Гамбия',
    GN: 'Гвинея',
    GP: 'Гваделупа',
    GQ: 'Экваториальная Гвинея',
    GR: 'Греция',
    GS: 'Южная Георгия и Южные Сандвичевы о-ва',
    GT: 'Гватемала',
    GU: 'Гуам',
    GW: 'Гвинея-Бисау',
    GY: 'Гайана',
    HK: 'Гонконг (САР)',
    HM: 'о-ва Херд и Макдональд',
    HN: 'Гондурас',
    HR: 'Хорватия',
    HT: 'Гаити',
    HU: 'Венгрия',
    ID: 'Индонезия',
    IE: 'Ирландия',
    IL: 'Израиль',
    IM: 'о-в Мэн',
    IN: 'Индия',
    IO: 'Британская территория в Индийском океане',
    IQ: 'Ирак',
    IR: 'Иран',
    IS: 'Исландия',
    IT: 'Италия',
    JE: 'Джерси',
    JM: 'Ямайка',
    JO: 'Иордания',
    JP: 'Япония',
    KE: 'Кения',
    KG: 'Киргизия',
    KH: 'Камбоджа',
    KI: 'Кирибати',
    KM: 'Коморы',
    KN: 'Сент-Китс и Невис',
    KP: 'КНДР',
    KR: 'Республика Корея',
    KW: 'Кувейт',
    KY: 'о-ва Кайман',
    KZ: 'Казахстан',
    LA: 'Лаос',
    LB: 'Ливан',
    LC: 'Сент-Люсия',
    LI: 'Лихтенштейн',
    LK: 'Шри-Ланка',
    LR: 'Либерия',
    LS: 'Лесото',
    LT: 'Литва',
    LU: 'Люксембург',
    LV: 'Латвия',
    LY: 'Ливия',
    MA: 'Марокко',
    MC: 'Монако',
    MD: 'Молдова',
    ME: 'Черногория',
    MF: 'Сен-Мартен',
    MG: 'Мадагаскар',
    MH: 'Маршалловы о-ва',
    MK: 'Северная Македония',
    ML: 'Мали',
    MM: 'Мьянма (Бирма)',
    MN: 'Монголия',
    MO: 'Макао (САР)',
    MP: 'Северные Марианские о-ва',
    MQ: 'Мартиника',
    MR: 'Мавритания',
    MS: 'Монтсеррат',
    MT: 'Мальта',
    MU: 'Маврикий',
    MV: 'Мальдивы',
    MW: 'Малави',
    MX: 'Мексика',
    MY: 'Малайзия',
    MZ: 'Мозамбик',
    NA: 'Намибия',
    NC: 'Новая Каледония',
    NE: 'Нигер',
    NF: 'о-в Норфолк',
    NG: 'Нигерия',
    NI: 'Никарагуа',
    NL: 'Нидерланды',
    NO: 'Норвегия',
    NP: 'Непал',
    NR: 'Науру',
    NU: 'Ниуэ',
    NZ: 'Новая Зеландия',
    OM: 'Оман',
    PA: 'Панама',
    PE: 'Перу',
    PF: 'Французская Полинезия',
    PG: 'Папуа — Новая Гвинея',
    PH: 'Филиппины',
    PK: 'Пакистан',
    PL: 'Польша',
    PM: 'Сен-Пьер и Микелон',
    PN: 'о-ва Питкэрн',
    PR: 'Пуэрто-Рико',
    PS: 'Палестинские территории',
    PT: 'Португалия',
    PW: 'Палау',
    PY: 'Парагвай',
    QA: 'Катар',
    RE: 'Реюньон',
    RO: 'Румыния',
    RS: 'Сербия',
    RU: 'Россия',
    RW: 'Руанда',
    SA: 'Саудовская Аравия',
    SB: 'Соломоновы о-ва',
    SC: 'Сейшельские о-ва',
    SD: 'Судан',
    SE: 'Швеция',
    SG: 'Сингапур',
    SH: 'о-в Св. Елены',
    SI: 'Словения',
    SJ: 'Шпицберген и Ян-Майен',
    SK: 'Словакия',
    SL: 'Сьерра-Леоне',
    SM: 'Сан-Марино',
    SN: 'Сенегал',
    SO: 'Сомали',
    SR: 'Суринам',
    SS: 'Южный Судан',
    ST: 'Сан-Томе и Принсипи',
    SV: 'Сальвадор',
    SX: 'Синт-Мартен',
    SY: 'Сирия',
    SZ: 'Эсватини',
    TC: 'Тёркс и Кайкос',
    TD: 'Чад',
    TF: 'Французские Южные территории',
    TG: 'Того',
    TH: 'Таиланд',
    TJ: 'Таджикистан',
    TK: 'Токелау',
    TL: 'Восточный Тимор',
    TM: 'Туркменистан',
    TN: 'Тунис',
    TO: 'Тонга',
    TR: 'Турция',
    TT: 'Тринидад и Тобаго',
    TV: 'Тувалу',
    TW: 'Тайвань',
    TZ: 'Танзания',
    UA: 'Украина',
    UG: 'Уганда',
    UM: 'Внешние малые о-ва (США)',
    US: 'Соединенные Штаты',
    UY: 'Уругвай',
    UZ: 'Узбекистан',
    VA: 'Ватикан',
    VC: 'Сент-Винсент и Гренадины',
    VE: 'Венесуэла',
    VG: 'Виргинские о-ва (Великобритания)',
    VI: 'Виргинские о-ва (США)',
    VN: 'Вьетнам',
    VU: 'Вануату',
    WF: 'Уоллис и Футуна',
    WS: 'Самоа',
    YE: 'Йемен',
    YT: 'Майотта',
    ZA: 'Южно-Африканская Республика',
    ZM: 'Замбия',
    ZW: 'Зимбабве',
  },
  uk: {
    AD: 'Андорра',
    AE: 'Обʼєднані Арабські Емірати',
    AF: 'Афганістан',
    AG: 'Антигуа і Барбуда',
    AI: 'Ангілья',
    AL: 'Албанія',
    AM: 'Вірменія',
    AO: 'Ангола',
    AQ: 'Антарктика',
    AR: 'Аргентина',
    AS: 'Американське Самоа',
    AT: 'Австрія',
    AU: 'Австралія',
    AW: 'Аруба',
    AX: 'Аландські Острови',
    AZ: 'Азербайджан',
    BA: 'Боснія і Герцеговина',
    BB: 'Барбадос',
    BD: 'Бангладеш',
    BE: 'Бельгія',
    BF: 'Буркіна-Фасо',
    BG: 'Болгарія',
    BH: 'Бахрейн',
    BI: 'Бурунді',
    BJ: 'Бенін',
    BL: 'Сен-Бартелемі',
    BM: 'Бермудські Острови',
    BN: 'Бруней',
    BO: 'Болівія',
    BQ: 'Карибські Нідерланди',
    BR: 'Бразилія',
    BS: 'Багамські Острови',
    BT: 'Бутан',
    BV: 'Острів Буве',
    BW: 'Ботсвана',
    BY: 'Білорусь',
    BZ: 'Беліз',
    CA: 'Канада',
    CC: 'Кокосові (Кілінг) Острови',
    CD: 'Конго – Кіншаса',
    CF: 'Центральноафриканська Республіка',
    CG: 'Конго – Браззавіль',
    CH: 'Швейцарія',
    CI: 'Кот-дʼІвуар',
    CK: 'Острови Кука',
    CL: 'Чилі',
    CM: 'Камерун',
    CN: 'Китай',
    CO: 'Колумбія',
    CR: 'Коста-Рика',
    CU: 'Куба',
    CV: 'Кабо-Верде',
    CW: 'Кюрасао',
    CX: 'Острів Різдва',
    CY: 'Кіпр',
    CZ: 'Чехія',
    DE: 'Німеччина',
    DJ: 'Джибуті',
    DK: 'Данія',
    DM: 'Домініка',
    DO: 'Домініканська Республіка',
    DZ: 'Алжир',
    EC: 'Еквадор',
    EE: 'Естонія',
    EG: 'Єгипет',
    EH: 'Західна Сахара',
    ER: 'Еритрея',
    ES: 'Іспанія',
    ET: 'Ефіопія',
    FI: 'Фінляндія',
    FJ: 'Фіджі',
    FK: 'Фолклендські Острови',
    FM: 'Мікронезія',
    FO: 'Фарерські Острови',
    FR: 'Франція',
    GA: 'Габон',
    GB: 'Велика Британія',
    GD: 'Гренада',
    GE: 'Грузія',
    GF: 'Французька Гвіана',
    GG: 'Гернсі',
    GH: 'Гана',
    GI: 'Гібралтар',
    GL: 'Гренландія',
    GM: 'Гамбія',
    GN: 'Гвінея',
    GP: 'Гваделупа',
    GQ: 'Екваторіальна Гвінея',
    GR: 'Греція',
    GS: 'Південна Джорджія та Південні Сандвічеві Острови',
    GT: 'Гватемала',
    GU: 'Гуам',
    GW: 'Гвінея-Бісау',
    GY: 'Гаяна',
    HK: 'Гонконг, ОАР Китаю',
    HM: 'Острови Герд і Макдоналд',
    HN: 'Гондурас',
    HR: 'Хорватія',
    HT: 'Гаїті',
    HU: 'Угорщина',
    ID: 'Індонезія',
    IE: 'Ірландія',
    IL: 'Ізраїль',
    IM: 'Острів Мен',
    IN: 'Індія',
    IO: 'Британська територія в Індійському Океані',
    IQ: 'Ірак',
    IR: 'Іран',
    IS: 'Ісландія',
    IT: 'Італія',
    JE: 'Джерсі',
    JM: 'Ямайка',
    JO: 'Йорданія',
    JP: 'Японія',
    KE: 'Кенія',
    KG: 'Киргизстан',
    KH: 'Камбоджа',
    KI: 'Кірибаті',
    KM: 'Комори',
    KN: 'Сент-Кітс і Невіс',
    KP: 'Північна Корея',
    KR: 'Південна Корея',
    KW: 'Кувейт',
    KY: 'Кайманові Острови',
    KZ: 'Казахстан',
    LA: 'Лаос',
    LB: 'Ліван',
    LC: 'Сент-Люсія',
    LI: 'Ліхтенштейн',
    LK: 'Шрі-Ланка',
    LR: 'Ліберія',
    LS: 'Лесото',
    LT: 'Литва',
    LU: 'Люксембург',
    LV: 'Латвія',
    LY: 'Лівія',
    MA: 'Марокко',
    MC: 'Монако',
    MD: 'Молдова',
    ME: 'Чорногорія',
    MF: 'Сен-Мартен',
    MG: 'Мадагаскар',
    MH: 'Маршаллові Острови',
    MK: 'Північна Македонія',
    ML: 'Малі',
    MM: 'Мʼянма (Бірма)',
    MN: 'Монголія',
    MO: 'Макао, ОАР Китаю',
    MP: 'Північні Маріанські Острови',
    MQ: 'Мартиніка',
    MR: 'Мавританія',
    MS: 'Монтсеррат',
    MT: 'Мальта',
    MU: 'Маврикій',
    MV: 'Мальдіви',
    MW: 'Малаві',
    MX: 'Мексика',
    MY: 'Малайзія',
    MZ: 'Мозамбік',
    NA: 'Намібія',
    NC: 'Нова Каледонія',
    NE: 'Нігер',
    NF: 'Острів Норфолк',
    NG: 'Нігерія',
    NI: 'Нікарагуа',
    NL: 'Нідерланди',
    NO: 'Норвегія',
    NP: 'Непал',
    NR: 'Науру',
    NU: 'Ніуе',
    NZ: 'Нова Зеландія',
    OM: 'Оман',
    PA: 'Панама',
    PE: 'Перу',
    PF: 'Французька Полінезія',
    PG: 'Папуа-Нова Гвінея',
    PH: 'Філіппіни',
    PK: 'Пакистан',
    PL: 'Польща',
    PM: 'Сен-Пʼєр і Мікелон',
    PN: 'Острови Піткерн',
    PR: 'Пуерто-Рико',
    PS: 'Палестинські території',
    PT: 'Португалія',
    PW: 'Палау',
    PY: 'Парагвай',
    QA: 'Катар',
    RE: 'Реюньйон',
    RO: 'Румунія',
    RS: 'Сербія',
    RU: 'Росія',
    RW: 'Руанда',
    SA: 'Саудівська Аравія',
    SB: 'Соломонові Острови',
    SC: 'Сейшельські Острови',
    SD: 'Судан',
    SE: 'Швеція',
    SG: 'Сінгапур',
    SH: 'Острів Святої Єлени',
    SI: 'Словенія',
    SJ: 'Шпіцберген та Ян-Маєн',
    SK: 'Словаччина',
    SL: 'Сьєрра-Леоне',
    SM: 'Сан-Марино',
    SN: 'Сенегал',
    SO: 'Сомалі',
    SR: 'Суринам',
    SS: 'Південний Судан',
    ST: 'Сан-Томе і Принсіпі',
    SV: 'Сальвадор',
    SX: 'Сінт-Мартен',
    SY: 'Сирія',
    SZ: 'Есватіні',
    TC: 'Острови Теркс і Кайкос',
    TD: 'Чад',
    TF: 'Французькі Південні Території',
    TG: 'Того',
    TH: 'Таїланд',
    TJ: 'Таджикистан',
    TK: 'Токелау',
    TL: 'Тимор-Лешті',
    TM: 'Туркменістан',
    TN: 'Туніс',
    TO: 'Тонга',
    TR: 'Туреччина',
    TT: 'Тринідад і Тобаго',
    TV: 'Тувалу',
    TW: 'Тайвань',
    TZ: 'Танзанія',
    UA: 'Україна',
    UG: 'Уганда',
    UM: 'Віддалені острови США',
    US: 'Сполучені Штати',
    UY: 'Уругвай',
    UZ: 'Узбекистан',
    VA: 'Ватикан',
    VC: 'Сент-Вінсент і Гренадіни',
    VE: 'Венесуела',
    VG: 'Британські Віргінські острови',
    VI: 'Віргінські Острови (США)',
    VN: 'Вʼєтнам',
    VU: 'Вануату',
    WF: 'Уолліс і Футуна',
    WS: 'Самоа',
    YE: 'Ємен',
    YT: 'Майотта',
    ZA: 'Південно-Африканська Республіка',
    ZM: 'Замбія',
    ZW: 'Зімбабве',
  },
  fr: {
    AD: 'Andorre',
    AE: 'Émirats arabes unis',
    AF: 'Afghanistan',
    AG: 'Antigua-et-Barbuda',
    AI: 'Anguilla',
    AL: 'Albanie',
    AM: 'Arménie',
    AO: 'Angola',
    AQ: 'Antarctique',
    AR: 'Argentine',
    AS: 'Samoa américaines',
    AT: 'Autriche',
    AU: 'Australie',
    AW: 'Aruba',
    AX: 'Îles Åland',
    AZ: 'Azerbaïdjan',
    BA: 'Bosnie-Herzégovine',
    BB: 'Barbade',
    BD: 'Bangladesh',
    BE: 'Belgique',
    BF: 'Burkina Faso',
    BG: 'Bulgarie',
    BH: 'Bahreïn',
    BI: 'Burundi',
    BJ: 'Bénin',
    BL: 'Saint-Barthélemy',
    BM: 'Bermudes',
    BN: 'Brunei',
    BO: 'Bolivie',
    BQ: 'Pays-Bas caribéens',
    BR: 'Brésil',
    BS: 'Bahamas',
    BT: 'Bhoutan',
    BV: 'Île Bouvet',
    BW: 'Botswana',
    BY: 'Biélorussie',
    BZ: 'Belize',
    CA: 'Canada',
    CC: 'Îles Cocos',
    CD: 'Congo-Kinshasa',
    CF: 'République centrafricaine',
    CG: 'Congo-Brazzaville',
    CH: 'Suisse',
    CI: 'Côte d’Ivoire',
    CK: 'Îles Cook',
    CL: 'Chili',
    CM: 'Cameroun',
    CN: 'Chine',
    CO: 'Colombie',
    CR: 'Costa Rica',
    CU: 'Cuba',
    CV: 'Cap-Vert',
    CW: 'Curaçao',
    CX: 'Île Christmas',
    CY: 'Chypre',
    CZ: 'Tchéquie',
    DE: 'Allemagne',
    DJ: 'Djibouti',
    DK: 'Danemark',
    DM: 'Dominique',
    DO: 'République dominicaine',
    DZ: 'Algérie',
    EC: 'Équateur',
    EE: 'Estonie',
    EG: 'Égypte',
    EH: 'Sahara occidental',
    ER: 'Érythrée',
    ES: 'Espagne',
    ET: 'Éthiopie',
    FI: 'Finlande',
    FJ: 'Fidji',
    FK: 'Îles Malouines',
    FM: 'Micronésie',
    FO: 'Îles Féroé',
    FR: 'France',
    GA: 'Gabon',
    GB: 'Royaume-Uni',
    GD: 'Grenade',
    GE: 'Géorgie',
    GF: 'Guyane française',
    GG: 'Guernesey',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GL: 'Groenland',
    GM: 'Gambie',
    GN: 'Guinée',
    GP: 'Guadeloupe',
    GQ: 'Guinée équatoriale',
    GR: 'Grèce',
    GS: 'Géorgie du Sud-et-les Îles Sandwich du Sud',
    GT: 'Guatemala',
    GU: 'Guam',
    GW: 'Guinée-Bissau',
    GY: 'Guyana',
    HK: 'R.A.S. chinoise de Hong Kong',
    HM: 'Îles Heard-et-MacDonald',
    HN: 'Honduras',
    HR: 'Croatie',
    HT: 'Haïti',
    HU: 'Hongrie',
    ID: 'Indonésie',
    IE: 'Irlande',
    IL: 'Israël',
    IM: 'Île de Man',
    IN: 'Inde',
    IO: 'Territoire britannique de l’océan Indien',
    IQ: 'Irak',
    IR: 'Iran',
    IS: 'Islande',
    IT: 'Italie',
    JE: 'Jersey',
    JM: 'Jamaïque',
    JO: 'Jordanie',
    JP: 'Japon',
    KE: 'Kenya',
    KG: 'Kirghizstan',
    KH: 'Cambodge',
    KI: 'Kiribati',
    KM: 'Comores',
    KN: 'Saint-Christophe-et-Niévès',
    KP: 'Corée du Nord',
    KR: 'Corée du Sud',
    KW: 'Koweït',
    KY: 'Îles Caïmans',
    KZ: 'Kazakhstan',
    LA: 'Laos',
    LB: 'Liban',
    LC: 'Sainte-Lucie',
    LI: 'Liechtenstein',
    LK: 'Sri Lanka',
    LR: 'Liberia',
    LS: 'Lesotho',
    LT: 'Lituanie',
    LU: 'Luxembourg',
    LV: 'Lettonie',
    LY: 'Libye',
    MA: 'Maroc',
    MC: 'Monaco',
    MD: 'Moldavie',
    ME: 'Monténégro',
    MF: 'Saint-Martin',
    MG: 'Madagascar',
    MH: 'Îles Marshall',
    MK: 'Macédoine du Nord',
    ML: 'Mali',
    MM: 'Myanmar (Birmanie)',
    MN: 'Mongolie',
    MO: 'R.A.S. chinoise de Macao',
    MP: 'Îles Mariannes du Nord',
    MQ: 'Martinique',
    MR: 'Mauritanie',
    MS: 'Montserrat',
    MT: 'Malte',
    MU: 'Maurice',
    MV: 'Maldives',
    MW: 'Malawi',
    MX: 'Mexique',
    MY: 'Malaisie',
    MZ: 'Mozambique',
    NA: 'Namibie',
    NC: 'Nouvelle-Calédonie',
    NE: 'Niger',
    NF: 'Île Norfolk',
    NG: 'Nigeria',
    NI: 'Nicaragua',
    NL: 'Pays-Bas',
    NO: 'Norvège',
    NP: 'Népal',
    NR: 'Nauru',
    NU: 'Niue',
    NZ: 'Nouvelle-Zélande',
    OM: 'Oman',
    PA: 'Panama',
    PE: 'Pérou',
    PF: 'Polynésie française',
    PG: 'Papouasie-Nouvelle-Guinée',
    PH: 'Philippines',
    PK: 'Pakistan',
    PL: 'Pologne',
    PM: 'Saint-Pierre-et-Miquelon',
    PN: 'Îles Pitcairn',
    PR: 'Porto Rico',
    PS: 'Territoires palestiniens',
    PT: 'Portugal',
    PW: 'Palaos',
    PY: 'Paraguay',
    QA: 'Qatar',
    RE: 'La Réunion',
    RO: 'Roumanie',
    RS: 'Serbie',
    RU: 'Russie',
    RW: 'Rwanda',
    SA: 'Arabie saoudite',
    SB: 'Îles Salomon',
    SC: 'Seychelles',
    SD: 'Soudan',
    SE: 'Suède',
    SG: 'Singapour',
    SH: 'Sainte-Hélène',
    SI: 'Slovénie',
    SJ: 'Svalbard et Jan Mayen',
    SK: 'Slovaquie',
    SL: 'Sierra Leone',
    SM: 'Saint-Marin',
    SN: 'Sénégal',
    SO: 'Somalie',
    SR: 'Suriname',
    SS: 'Soudan du Sud',
    ST: 'Sao Tomé-et-Principe',
    SV: 'Salvador',
    SX: 'Saint-Martin (partie néerlandaise)',
    SY: 'Syrie',
    SZ: 'Eswatini',
    TC: 'Îles Turques-et-Caïques',
    TD: 'Tchad',
    TF: 'Terres australes françaises',
    TG: 'Togo',
    TH: 'Thaïlande',
    TJ: 'Tadjikistan',
    TK: 'Tokelau',
    TL: 'Timor oriental',
    TM: 'Turkménistan',
    TN: 'Tunisie',
    TO: 'Tonga',
    TR: 'Turquie',
    TT: 'Trinité-et-Tobago',
    TV: 'Tuvalu',
    TW: 'Taïwan',
    TZ: 'Tanzanie',
    UA: 'Ukraine',
    UG: 'Ouganda',
    UM: 'Îles mineures éloignées des États-Unis',
    US: 'États-Unis',
    UY: 'Uruguay',
    UZ: 'Ouzbékistan',
    VA: 'État de la Cité du Vatican',
    VC: 'Saint-Vincent-et-les Grenadines',
    VE: 'Venezuela',
    VG: 'Îles Vierges britanniques',
    VI: 'Îles Vierges des États-Unis',
    VN: 'Viêt Nam',
    VU: 'Vanuatu',
    WF: 'Wallis-et-Futuna',
    WS: 'Samoa',
    YE: 'Yémen',
    YT: 'Mayotte',
    ZA: 'Afrique du Sud',
    ZM: 'Zambie',
    ZW: 'Zimbabwe',
  },
};

function normalizeLocale(locale?: string) {
  if (!locale) return 'en';
  return locale.toLowerCase().split('-')[0];
}

export function getCountryName(countryCode: string, locale?: string) {
  const normalizedCode = countryCode.toUpperCase();
  const normalizedLocale = normalizeLocale(locale);
  const localeMap = COUNTRY_NAMES_BY_LOCALE[normalizedLocale] || COUNTRY_NAMES_BY_LOCALE.en;

  return localeMap[normalizedCode] || COUNTRY_NAMES_BY_LOCALE.en[normalizedCode] || countryCode;
}
